[build]
  command = "yarn rw db up --no-db-client --auto-approve && yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[plugins]]
package = 'netlify-plugin-heroku-database-url'
  [plugins.inputs]
  app_name = "netlify-deployed"

[[plugins]]
package = 'netlify-plugin-redwoodjs-env-validator'

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'api/prisma/schema.prisma'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/deploy"
  to = "/.netlify/functions/deploy"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "/.netlify/functions/register"
  status = 200
  force = true

[[redirects]]
  from = "/signin"
  to = "/.netlify/functions/signin"
  status = 200
  force = true
